# Generated by Django 4.2.11 on 2026-05-02 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("subscription_id", models.UUIDField()),
                ("gateway", models.CharField(max_length=50)),
                (
                    "gateway_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(blank=True, max_length=255, unique=True),
                ),
                (
                    "idempotency_key",
                    models.CharField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["idempotency_key"],
                        name="payments_pa_idempot_d55485_idx",
                    ),
                    models.Index(
                        fields=["gateway_payment_id"],
                        name="payments_pa_gateway_9ebf66_idx",
                    ),
                    models.Index(
                        fields=["subscription_id"],
                        name="payments_pa_subscri_77dc11_idx",
                    ),
                ],
            },
        ),
    ]
