# Generated by Django 4.2.11 on 2026-05-02 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                default=uuid.uuid4, editable=False, max_length=255, unique=True
            ),
        ),
    ]
