# Generated by Django 4.2.11 on 2026-05-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
