# Generated by Django 4.2.11 on 2026-05-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_idempotency_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway_payment_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
