# Generated by Django 4.2.11 on 2026-04-29 20:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TariffPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Basic, Standard, Premium", unique=True
                    ),
                ),
                ("speed_mbps", models.IntegerField(help_text="Download speed in Mbps")),
                (
                    "data_limit_gb",
                    models.IntegerField(
                        blank=True,
                        help_text="Data limit in GB. Leave blank for unlimited.",
                        null=True,
                    ),
                ),
                ("price_monthly", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price_annual", models.DecimalField(decimal_places=2, max_digits=8)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        condition=models.Q(("is_active", True)),
                        fields=["is_active"],
                        name="idx_active_plans",
                    )
                ],
            },
        ),
    ]
